### PR TITLE
Make spotipy working again

### PR DESCRIPTION
**Pull request by tuxpeople**
This PR is a result of my issue #206 and [this](https://twitter.com/tdeutsch/status/1293083845609349120) Twitter conversation.

The following has been changed:
- Buster instead of Jessie
- Leave apt source list of Mopidy in place for later upgrade
- Change from Python2 to Python3
- Replaced broken ttsgpio with raspberry-gpio
- Removed the use of patch. Instead of this, the script now simply creates a config file containing all the stuff needed. Mopidy would then use it's defaults for the rest.
- added client_id and client_secret

Caution:
- I tested it on my pirate radio. It should receive more testing
- I'm not a pro. Someone should look over my code
- On my radio, volume down ist not working. Maybe my bad soldering skills caused this, as all other buttons are working.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thanks for tackling this- you don't know how helpful you've been!

I successfully ran this installer for default audio output and everything seems to work fine- the only thing that needs changing in that regard, as far as I can tell, is replacing "autoaudiosink" with "alsasink" because I didn't have audio out of the 3.5mm jack at first. This doesn't apply to configuring stuff like Pirate Radio though, I don't think.

I will have to dig up a Pirate Radio and verify with that. Your GPIO configuration looks correct to me- but Mopidy-Raspberry-GPIO has only been battle tested with the new Pirate Audio boards- heads or tails your soldering or my code 😆

**Comment by tuxpeople** [comment]
I'm happy to hear it's useful. I only tested it with my pirate radio (which does not have a 3.5mm jack). I'll test if I've hear something on my pirate radio speaker with alsasink.

**Comment by tuxpeople** [comment]
I've audio with alsasink as well.

**Comment by Gadgetoid** [comment]
Either way, looks like this is *far* less broken than the previous version so I'll merge what we have so far and see how it goes. Thank you again!

**Pull request merged**
